name: Build

on:
  pull_request:
    branches:
      "master"
  push:
    branches:
      "master"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://testing.allure.aws.qameta.in
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 2677
      - run: allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: build/allure-results
